[package]
name = "newengine-project-runtime"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "Project manifest loading and Asset VFS mount integration for NewEngine"

[dependencies]
newengine-assets = { path = "../newengine-assets" }
newengine-project-api = { path = "../newengine-project-api" }
serde_json = "1"
toml = "0.8"

