[package]
name = "newengine-previews"
version = "0.1.0"
readme = "README.md"
edition = "2021"

[dependencies]
parking_lot = "0.12"
bytemuck = { version = "1.23", features = ["derive"] }
newengine-core = { path = "../newengine-core" }
newengine-plugin-host = { path = "../newengine-plugin-host" }
newengine-ui = { path = "../newengine-ui" }
newengine-assets = { path = "../newengine-assets" }
newengine-primitives = { path = "../newengine-primitives" }
newengine-math = { path = "../newengine-math" }
newengine-shader-compiler = { path = "../newengine-shader-compiler" }
blake3 = "1.5.5"


