[package]
name = "newengine-render-runtime-adapter"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "Service-backed render capability runtime adapter for NewEngine"

[dependencies]
newengine-core = { path = "../newengine-core", default-features = false, features = ["render-api"] }
newengine-plugin-api = { path = "../newengine-plugin-api" }
newengine-plugin-host = { path = "../newengine-plugin-host" }
newengine-render-api = { path = "../newengine-render-api" }
newengine-runtime-adapter-core = { path = "../newengine-runtime-adapter-core" }
newengine-ulog-api = { path = "../newengine-ulog-api" }
