[package]
name = "newengine-asset-format-catalog-nef8"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
newengine-assets = { path = "../newengine-assets" }
newengine-assets-api = { path = "../newengine-assets-api" }
newengine-plugin-api = { path = "../newengine-plugin-api" }
newengine_asset_format_ytd = { package = "newengine-asset-format-ytd", path = "../newengine-asset-format-ytd" }
newengine_asset_format_ydd = { package = "newengine-asset-format-ydd", path = "../newengine-asset-format-ydd" }
newengine_asset_format_ydr = { package = "newengine-asset-format-ydr", path = "../newengine-asset-format-ydr" }
newengine_asset_format_yft = { package = "newengine-asset-format-yft", path = "../newengine-asset-format-yft" }
newengine_asset_format_ybn = { package = "newengine-asset-format-ybn", path = "../newengine-asset-format-ybn" }
newengine_asset_format_ytyp = { package = "newengine-asset-format-ytyp", path = "../newengine-asset-format-ytyp" }
newengine_asset_format_nemat = { package = "newengine-asset-format-nemat", path = "../newengine-asset-format-nemat" }
newengine_asset_format_neui = { package = "newengine-asset-format-neui", path = "../newengine-asset-format-neui" }
newengine_asset_format_ymap = { package = "newengine-asset-format-ymap", path = "../newengine-asset-format-ymap" }
newengine_asset_format_ymf = { package = "newengine-asset-format-ymf", path = "../newengine-asset-format-ymf" }
newengine_asset_format_ymt = { package = "newengine-asset-format-ymt", path = "../newengine-asset-format-ymt" }
newengine_asset_format_ycd = { package = "newengine-asset-format-ycd", path = "../newengine-asset-format-ycd" }
newengine_asset_format_yed = { package = "newengine-asset-format-yed", path = "../newengine-asset-format-yed" }
newengine_asset_format_yfd = { package = "newengine-asset-format-yfd", path = "../newengine-asset-format-yfd" }
newengine_asset_format_yld = { package = "newengine-asset-format-yld", path = "../newengine-asset-format-yld" }
newengine_asset_format_ypdb = { package = "newengine-asset-format-ypdb", path = "../newengine-asset-format-ypdb" }
newengine_asset_format_yvr = { package = "newengine-asset-format-yvr", path = "../newengine-asset-format-yvr" }
newengine_asset_format_ywr = { package = "newengine-asset-format-ywr", path = "../newengine-asset-format-ywr" }
newengine_asset_format_ysc = { package = "newengine-asset-format-ysc", path = "../newengine-asset-format-ysc" }
newengine_asset_format_ybd = { package = "newengine-asset-format-ybd", path = "../newengine-asset-format-ybd" }
newengine_asset_format_ytf = { package = "newengine-asset-format-ytf", path = "../newengine-asset-format-ytf" }
newengine_asset_format_nepak = { package = "newengine-asset-format-nepak", path = "../newengine-asset-format-nepak" }


[features]
default = []
