[package]
name = "newengine-game-runtime"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "Standalone game composition profile for NewEngine runtime host"

[dependencies]
log = "0.4"
newengine-assets = { path = "../newengine-assets" }
newengine-core = { path = "../newengine-core" }
newengine-plugin-host = { path = "../newengine-plugin-host" }
newengine-runtime-host = { path = "../newengine-runtime-host" }
newengine-editor-runtime = { path = "../newengine-editor-runtime", default-features = false, features = ["runtime-core"] }
newengine-ui = { path = "../newengine-ui", default-features = false }
