#![forbid(unsafe_op_in_unsafe_fn)]

//! AssetManager service contract constants.
//!
//! This module re-exports the canonical constants from
//! `newengine-assets-api`; the API crate remains the only source of truth.

pub use newengine_assets_api::{
    asset_graph_method, file_type_method, method, ASSET_BACKEND_CAPABILITY_ID, ASSET_BACKEND_SERVICE_SPEC,
    ASSET_TYPES_SERVICE_METHODS, ASSET_TYPES_BACKEND_CAPABILITY_ID,
    ASSET_TYPES_BACKEND_SERVICE_SPEC, ASSET_TYPES_RUNTIME_CONTRACT_SPEC,
    ASSET_TYPES_RUNTIME_REQUIREMENT_SPEC, ASSET_TYPES_SERVICE_ID, ASSET_GRAPH_BACKEND_CAPABILITY_ID,
    ASSET_GRAPH_SERVICE_ID, ASSET_GRAPH_SERVICE_METHODS, ASSET_METHOD_PREFIX,
    ASSET_PROVIDER_SERVICE_ID, ASSET_RUNTIME_CONTRACT_SPEC, ASSET_SERVICE_ID,
    ASSETS_DEPENDENCIES_BACKEND_CAPABILITY_ID, ASSETS_DEPENDENCIES_BACKEND_SERVICE_SPEC,
    ASSETS_DEPENDENCIES_RUNTIME_CONTRACT, ASSETS_DEPENDENCIES_SERVICE_ID,
    ASSETS_DIRTY_SCAN_CAPABILITY_ID, ASSETS_IMPORT_LIFECYCLE_CAPABILITY_ID,
    ASSETS_IMPORT_QUEUE_BACKEND_CAPABILITY_ID, ASSETS_IMPORT_QUEUE_BACKEND_SERVICE_SPEC,
    ASSETS_IMPORT_QUEUE_RUNTIME_CONTRACT, ASSETS_IMPORT_QUEUE_SERVICE_ID,
    ASSETS_PACKAGE_WRITER_BACKEND_SERVICE_SPEC, ASSETS_PACKAGE_WRITER_CAPABILITY_ID,
    ASSETS_PACKAGE_WRITER_RUNTIME_CONTRACT, ASSETS_PACKAGE_WRITER_SERVICE_ID,
    ASSETS_REIMPORT_CAPABILITY_ID, ASSETS_THUMBNAIL_CAPABILITY_ID,
    ASSETS_UID_BACKEND_CAPABILITY_ID, ASSETS_UID_BACKEND_SERVICE_SPEC, ASSETS_UID_RUNTIME_CONTRACT,
    ASSETS_UID_SERVICE_ID, ASSETS_UI_BACKEND_CAPABILITY_ID, ASSETS_UI_RUNTIME_CONTRACT,
    ASSETS_UI_SERVICE_ID, ASSETS_UI_SERVICE_METHODS, assets_ui_method,
    ENGINE_ASSET_TYPES_SERVICE_ID, ENGINE_ASSETS_DEPENDENCIES_SERVICE_ID,
    ENGINE_ASSETS_GRAPH_SERVICE_ID, ENGINE_ASSET_SERVICE_ID, ENGINE_ASSETS_DEFINITIONS_SERVICE_ID,
    ENGINE_ASSETS_IMPORT_QUEUE_SERVICE_ID, ENGINE_ASSETS_MAPS_SERVICE_ID,
    ENGINE_ASSETS_MATERIALS_SERVICE_ID, ENGINE_ASSETS_MODELS_SERVICE_ID,
    ENGINE_ASSETS_PACKAGE_WRITER_SERVICE_ID, ENGINE_ASSETS_TEXTURES_SERVICE_ID,
    ENGINE_ASSETS_UID_SERVICE_ID, REQUIRED_RUNTIME_METHODS_V1,
};
