#![forbid(unsafe_op_in_unsafe_fn)]

//! AssetManager service contract constants.
//!
//! This module re-exports the canonical constants from
//! `newengine-assets-api`; the API crate remains the only source of truth.

pub use newengine_assets_api::{
    asset_graph_method, file_type_method, method, ASSET_BACKEND_CAPABILITY_ID, ASSET_BACKEND_SERVICE_SPEC,
    ASSET_FILE_TYPE_SERVICE_METHODS, ASSET_FILE_TYPES_BACKEND_CAPABILITY_ID,
    ASSET_FILE_TYPES_BACKEND_SERVICE_SPEC, ASSET_FILE_TYPES_RUNTIME_CONTRACT_SPEC,
    ASSET_FILE_TYPES_RUNTIME_REQUIREMENT_SPEC, ASSET_FILE_TYPES_SERVICE_ID, ASSET_GRAPH_BACKEND_CAPABILITY_ID,
    ASSET_GRAPH_SERVICE_ID, ASSET_GRAPH_SERVICE_METHODS, ASSET_METHOD_PREFIX,
    ASSET_PROVIDER_SERVICE_ID, ASSET_RUNTIME_CONTRACT_SPEC, ASSET_SERVICE_ID,
    ASSETS_UI_BACKEND_CAPABILITY_ID, ASSETS_UI_RUNTIME_CONTRACT, ASSETS_UI_SERVICE_ID, ASSETS_UI_SERVICE_METHODS, assets_ui_method,
    ENGINE_ASSET_FILE_TYPES_SERVICE_ID, ENGINE_ASSETS_GRAPH_SERVICE_ID, ENGINE_ASSET_SERVICE_ID, ENGINE_ASSETS_DEFINITIONS_SERVICE_ID,
    ENGINE_ASSETS_MAPS_SERVICE_ID, ENGINE_ASSETS_MATERIALS_SERVICE_ID, ENGINE_ASSETS_MODELS_SERVICE_ID, ENGINE_ASSETS_TEXTURES_SERVICE_ID,
    REQUIRED_RUNTIME_METHODS_V1,
};
