[package]
name = "newengine-plugin-api"
version = "0.1.0"
readme = "README.md"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
newengine-contract-api = { path = "../newengine-contract-api" }
abi_stable = "0.11"
newengine-service-api = { path = "../newengine-service-api" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
