[package]
name = "newengine-modules-render-vulkan-ash"
version = "0.3.0"
readme = "README.md"
edition = "2021"

[dependencies]
newengine-core = { path = "../newengine-core" }
newengine-plugin-host = { path = "../newengine-plugin-host" }
newengine-ui = { path = "../newengine-ui" }
newengine-assets = { path = "../newengine-assets" }
ash = "0.38"
ash-window = "0.13"
raw-window-handle = "0.6"
thiserror = "2.0.18"
log = "0.4.29"
bytemuck = "1.24.0"
shaderc = "0.10.1"
blake3 = "1.5.5"


