[package]
name = "vulkan_renderer"
version = "0.3.0"
readme = "README.md"
edition = "2021"
build = "build.rs"
description = "NewEngine vulkan render plugin"
license = "MIT OR Apache-2.0"

[dependencies]
newengine-plugin-api = { path = "../newengine-plugin-api" }
newengine-platform-api = { path = "../newengine-platform-api" }
newengine-render-api = { path = "../newengine-render-api" }
newengine-assets = { path = "../newengine-assets" }
newengine-ui = { path = "../newengine-ui" }
ash = "0.38"
ash-window = "0.13"
abi_stable = { version = "0.11" }
raw-window-handle = "0.6"
thiserror = "2.0.18"
log = "0.4.29"
bytemuck = "1.24.0"
shaderc = "0.10.1"
blake3 = "1.5.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[lib]
name = "vulkan_renderer"
crate-type = ["rlib", "cdylib"]

[build-dependencies]
embed-resource = "3.0.6"