#![forbid(unsafe_op_in_unsafe_fn)]

use newengine_core::render::TextureFormat;

/// Runtime renderer quality constants for the current Vulkan V3 forward path.
///
/// This is deliberately a small declarative profile instead of scattering magic
/// values through shadow planning, shader setup and scene tuning. The target
/// architecture is a full RenderSettings/quality-profile resource, but constants
/// here keep this pass safe and compile-local.
pub(crate) const SHADOW_MAP_COLOR_FORMAT: TextureFormat = TextureFormat::Rgba16Float;
pub(crate) const SHADOW_STRENGTH_MAX: f32 = 0.70;
pub(crate) const SHADOW_SOFTNESS_MAX: f32 = 1.25;
pub(crate) const SHADOW_RESOLUTION_MIN: u32 = 256;
pub(crate) const SHADOW_RESOLUTION_MAX: u32 = 4096;

/// Maximum material mip levels generated by the Vulkan upload path.
/// This removes distant texture shimmer while keeping memory predictable until
/// streaming texture residency and per-material LOD budgets are implemented.
pub(crate) const MATERIAL_TEXTURE_MAX_MIP_LEVELS: u32 = 12;
