#![forbid(unsafe_op_in_unsafe_fn)]

use newengine_core::render::TextureFormat;

/// Runtime renderer quality constants for the current Vulkan forward path.
///
/// This is deliberately a small declarative profile instead of scattering magic
/// values through shadow planning, shader setup and scene tuning. The target
/// architecture is a full RenderSettings/quality-profile resource, but constants
/// here keep this pass safe and compile-local.
pub(crate) const SHADOW_MAP_COLOR_FORMAT: TextureFormat = TextureFormat::Rgba16Float;
pub(crate) const SHADOW_STRENGTH_MAX: f32 = 0.70;
pub(crate) const SHADOW_SOFTNESS_MAX: f32 = 1.25;
pub(crate) const SHADOW_RESOLUTION_MIN: u32 = 256;
pub(crate) const SHADOW_RESOLUTION_MAX: u32 = 4096;

/// Maximum material mip levels generated by the Vulkan upload path.
/// This removes distant texture shimmer while keeping memory predictable until
/// streaming texture residency and per-material LOD budgets are implemented.
pub(crate) const MATERIAL_TEXTURE_MAX_MIP_LEVELS: u32 = 8;


/// Loading-screen burst budget for *starting* material imports.
///
/// Starting an AssetManager request is cheap and lets importers/IO work overlap
/// while the native loading screen is still active. Decoding/GPU upload remains
/// separately frame-budgeted so a single render tick does not turn into a long
/// synchronous import stall.
pub(crate) const MATERIAL_TEXTURE_IMPORT_START_BURST: u32 = 64;

/// Sky/environment maps are visually important but should not block playable
/// world handoff. They are downscaled and uploaded lazily when large.
pub(crate) const SKY_TEXTURE_MAX_DIMENSION: u32 = 2048;

/// Large material textures are capped until renderer-native compressed texture
/// residency is available. 1024² content passes through unchanged; oversized
/// DDS/environment sources are reduced before GPU upload.
pub(crate) const MATERIAL_TEXTURE_MAX_DIMENSION: u32 = 2048;

/// The first playable frames should present quickly; expensive shadow cache
/// population is staged immediately after initial visibility and material
/// bindings are warm. This mirrors the reference renderer's phased draw-list
/// warmup instead of doing every heavy pass on frame one.
pub(crate) const SHADOW_WARMUP_DEFER_FRAMES: u8 = 2;
