[package]
name = "newengine-model-import-northstar"
version = "0.1.0"
edition = "2021"
description = "Offline NorthStar PC source importer for NewEngine native model assets"

[dependencies]
newengine-asset-format-nef8 = { path = "../newengine-asset-format-nef8" }
newengine-assets-api = { path = "../newengine-assets-api" }
newengine-math = { path = "../newengine-math" }
newengine-texture-container = { path = "../newengine-texture-container" }
flate2 = "1"
newengine-model-skeleton-api = { path = "../newengine-model-skeleton-api" }
serde_json = "1"
blake3 = "1"

[dev-dependencies]
newengine-asset-format-nehair = { path = "../newengine-asset-format-nehair" }
roxmltree = "0.20"
