#![forbid(unsafe_op_in_unsafe_fn)]

use newengine_math::{EulerRot, Mat4, Quat, Vec3};

/// Local transform relative to parent.
#[derive(Clone, Copy, Debug)]
pub struct Transform {
    pub position: Vec3,
    pub rotation: Quat,
    pub scale: Vec3,
}

impl Default for Transform {
    #[inline]
    fn default() -> Self {
        Self {
            position: Vec3::ZERO,
            rotation: Quat::IDENTITY,
            scale: Vec3::ONE,
        }
    }
}

impl Transform {
    /// Builds a transform from yaw/pitch/roll (radians) using engine-default conventions.
    #[inline]
    pub fn from_yaw_pitch_roll(
        position: Vec3,
        yaw: f32,
        pitch: f32,
        roll: f32,
        scale: Vec3,
    ) -> Self {
        let rotation = Quat::from_euler(EulerRot::YXZ, yaw, pitch, roll);
        Self {
            position,
            rotation,
            scale,
        }
    }

    /// Returns (yaw, pitch, roll) in radians using engine-default conventions.
    #[inline]
    pub fn yaw_pitch_roll(self) -> (f32, f32, f32) {
        self.rotation.to_euler(EulerRot::YXZ)
    }

    #[inline]
    pub fn to_mat4(self) -> Mat4 {
        Mat4::from_scale_rotation_translation(self.scale, self.rotation, self.position)
    }
}

/// World-space transform (derived).
#[derive(Clone, Copy, Debug)]
pub struct GlobalTransform(pub Mat4);

impl Default for GlobalTransform {
    #[inline]
    fn default() -> Self {
        Self(Mat4::IDENTITY)
    }
}

/// Parent link (tree).
#[cfg(feature = "ecs")]
#[derive(Clone, Copy, Debug)]
pub struct Parent(pub newengine_ecs::EntityId);

/// Children list (maintained by editor/gameplay code).
#[cfg(feature = "ecs")]
#[derive(Clone, Debug, Default)]
pub struct Children(pub Vec<newengine_ecs::EntityId>);

/// Marks a node as needing recomputation (optional; currently used as a hint only).
#[cfg(feature = "ecs")]
#[derive(Clone, Copy, Debug, Default)]
pub struct TransformDirty;

/// Convenience world-space pose derived from `GlobalTransform`.
///
/// Generated by `propagate_transforms()` together with `GlobalTransform`.
#[derive(Clone, Copy, Debug, Default)]
pub struct WorldPose {
    pub world_pos: Vec3,
    /// Yaw around +Y (radians).
    pub yaw: f32,
    /// Pitch around +X (radians).
    pub pitch: f32,
    /// Roll around +Z (radians).
    pub roll: f32,
    pub world_scale: Vec3,
}
