[package]
name = "renderer-demo"
version = "0.1.0"
edition = "2021"
description = "NewEngine renderer demo launcher: shaded lit scene smoke target"
authors = ["Take Some()"]
license = "Proprietary"

[package.metadata.newengine.winres]
icon = "assets/editor.ico"

[dependencies]
newengine-core = { workspace = true }
newengine-game-ready-profile = { workspace = true }
newengine-runtime-host = { workspace = true, default-features = false, features = ["full-runtime"] }
newengine-windowed-host-runtime = { workspace = true, default-features = false, features = ["prestart-window-egui", "window-icon"] }
newengine-ui = { workspace = true, default-features = false }

[build-dependencies]
embed-resource = "2"
