[package]
name = "newengine-materials"
version = "0.1.0"
readme = "README.md"
edition = "2021"

[features]
# Enables serde support for material descriptors.
serde = ["dep:serde", "dep:serde_json"]

[dependencies]
parking_lot = "0.12"
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
