use newengine_world_environment_api::{PrecipitationKind, WeatherKind};

use super::{phenomena::*, WeatherPatternDescriptor};

pub(super) const PATTERNS: &[WeatherPatternDescriptor] = &[
    WeatherPatternDescriptor {
        id: "weather.clear.dry_high_pressure",
        kind: WeatherKind::Clear,
        weather_visual_ref: "weather/clear.yweather@dry_high_pressure",
        intensity_min: 0.00,
        intensity_max: 0.18,
        cloud_floor: 0.02,
        cloud_ceiling: 0.30,
        overcast_bias: 0.00,
        precipitation_kind: PrecipitationKind::None,
        precipitation_factor: 0.0,
        thunder_factor: 0.0,
        wetness_factor: 0.0,
        snow_factor: 0.0,
        fog_factor: 0.0,
        haze_factor: 0.04,
        wind_base_mps: 1.2,
        wind_gain_mps: 1.8,
        gust_base: 0.04,
        gust_gain: 0.10,
        visibility_factor: 1.0,
        tags: &["weather.clear", "visibility.normal"],
        required_assets: &["sky/clear_day.ysky@gradient"],
        phenomena: PHENOMENA_CLEAR,
    },
    WeatherPatternDescriptor {
        id: "weather.cloudy.fair_cumulus",
        kind: WeatherKind::Cloudy,
        weather_visual_ref: "weather/cloudy.yweather@fair_cumulus",
        intensity_min: 0.30,
        intensity_max: 0.62,
        cloud_floor: 0.26,
        cloud_ceiling: 0.64,
        overcast_bias: 0.10,
        precipitation_kind: PrecipitationKind::None,
        precipitation_factor: 0.0,
        thunder_factor: 0.0,
        wetness_factor: 0.0,
        snow_factor: 0.0,
        fog_factor: 0.0,
        haze_factor: 0.09,
        wind_base_mps: 2.2,
        wind_gain_mps: 2.3,
        gust_base: 0.08,
        gust_gain: 0.18,
        visibility_factor: 0.88,
        tags: &["weather.cloudy", "cloud.broken"],
        required_assets: &["clouds/cumulus_fields.ycloud@broken_cumulus"],
        phenomena: PHENOMENA_CLOUDY,
    },
    WeatherPatternDescriptor {
        id: "weather.overcast.stratus_deck",
        kind: WeatherKind::Overcast,
        weather_visual_ref: "weather/overcast.yweather@stratus_deck",
        intensity_min: 0.55,
        intensity_max: 0.84,
        cloud_floor: 0.68,
        cloud_ceiling: 0.94,
        overcast_bias: 0.34,
        precipitation_kind: PrecipitationKind::None,
        precipitation_factor: 0.0,
        thunder_factor: 0.0,
        wetness_factor: 0.0,
        snow_factor: 0.0,
        fog_factor: 0.02,
        haze_factor: 0.18,
        wind_base_mps: 2.8,
        wind_gain_mps: 3.0,
        gust_base: 0.12,
        gust_gain: 0.25,
        visibility_factor: 0.72,
        tags: &["weather.overcast", "cloud.overcast"],
        required_assets: &["clouds/stratus_fields.ycloud@overcast_sheet"],
        phenomena: PHENOMENA_OVERCAST,
    },
    WeatherPatternDescriptor {
        id: "weather.rain.nimbostratus",
        kind: WeatherKind::Rain,
        weather_visual_ref: "weather/rain.yweather@nimbostratus",
        intensity_min: 0.48,
        intensity_max: 0.92,
        cloud_floor: 0.74,
        cloud_ceiling: 0.98,
        overcast_bias: 0.46,
        precipitation_kind: PrecipitationKind::Rain,
        precipitation_factor: 0.68,
        thunder_factor: 0.02,
        wetness_factor: 0.92,
        snow_factor: 0.0,
        fog_factor: 0.04,
        haze_factor: 0.26,
        wind_base_mps: 3.4,
        wind_gain_mps: 4.8,
        gust_base: 0.18,
        gust_gain: 0.32,
        visibility_factor: 0.46,
        tags: &["weather.rain", "surface.wet", "audio.rain"],
        required_assets: &[
            "audio/weather.ybank@rain",
            "materials/wetness.nemat@default",
        ],
        phenomena: PHENOMENA_RAIN,
    },
    WeatherPatternDescriptor {
        id: "weather.storm.cumulonimbus",
        kind: WeatherKind::Storm,
        weather_visual_ref: "weather/storm.yweather@cumulonimbus",
        intensity_min: 0.70,
        intensity_max: 1.00,
        cloud_floor: 0.88,
        cloud_ceiling: 1.00,
        overcast_bias: 0.62,
        precipitation_kind: PrecipitationKind::Rain,
        precipitation_factor: 0.92,
        thunder_factor: 0.45,
        wetness_factor: 1.00,
        snow_factor: 0.0,
        fog_factor: 0.04,
        haze_factor: 0.32,
        wind_base_mps: 6.5,
        wind_gain_mps: 8.0,
        gust_base: 0.36,
        gust_gain: 0.58,
        visibility_factor: 0.26,
        tags: &[
            "weather.storm",
            "surface.wet",
            "audio.rain_heavy",
            "ai.shelter_preferred",
        ],
        required_assets: &[
            "clouds/cumulonimbus.ycloud@storm_core",
            "audio/weather.ybank@thunder",
            "audio/weather.ybank@rain",
            "materials/wetness.nemat@storm",
        ],
        phenomena: PHENOMENA_STORM,
    },
    WeatherPatternDescriptor {
        id: "weather.fog.ground_radiation",
        kind: WeatherKind::Fog,
        weather_visual_ref: "weather/fog.yweather@ground_radiation",
        intensity_min: 0.42,
        intensity_max: 0.90,
        cloud_floor: 0.04,
        cloud_ceiling: 0.26,
        overcast_bias: 0.18,
        precipitation_kind: PrecipitationKind::None,
        precipitation_factor: 0.0,
        thunder_factor: 0.0,
        wetness_factor: 0.06,
        snow_factor: 0.0,
        fog_factor: 0.62,
        haze_factor: 0.36,
        wind_base_mps: 0.5,
        wind_gain_mps: 1.4,
        gust_base: 0.02,
        gust_gain: 0.06,
        visibility_factor: 0.18,
        tags: &["weather.fog", "visibility.low", "ai.visibility_reduced"],
        required_assets: &["weather/fog.yweather@ground_radiation"],
        phenomena: PHENOMENA_FOG,
    },
    WeatherPatternDescriptor {
        id: "weather.snow.stratiform",
        kind: WeatherKind::Snow,
        weather_visual_ref: "weather/snow.yweather@stratiform",
        intensity_min: 0.50,
        intensity_max: 0.88,
        cloud_floor: 0.72,
        cloud_ceiling: 0.97,
        overcast_bias: 0.42,
        precipitation_kind: PrecipitationKind::Snow,
        precipitation_factor: 0.58,
        thunder_factor: 0.0,
        wetness_factor: 0.20,
        snow_factor: 0.84,
        fog_factor: 0.08,
        haze_factor: 0.24,
        wind_base_mps: 2.2,
        wind_gain_mps: 4.0,
        gust_base: 0.10,
        gust_gain: 0.24,
        visibility_factor: 0.36,
        tags: &["weather.snow", "surface.snow", "visibility.low"],
        required_assets: &[
            "clouds/snow_bands.ycloud@stratiform",
            "audio/weather.ybank@snow",
        ],
        phenomena: PHENOMENA_SNOW,
    },
    WeatherPatternDescriptor {
        id: "weather.dust_storm.front",
        kind: WeatherKind::DustStorm,
        weather_visual_ref: "weather/dust.yweather@front",
        intensity_min: 0.58,
        intensity_max: 0.94,
        cloud_floor: 0.00,
        cloud_ceiling: 0.18,
        overcast_bias: 0.30,
        precipitation_kind: PrecipitationKind::Dust,
        precipitation_factor: 0.72,
        thunder_factor: 0.0,
        wetness_factor: 0.0,
        snow_factor: 0.0,
        fog_factor: 0.18,
        haze_factor: 0.64,
        wind_base_mps: 7.0,
        wind_gain_mps: 9.0,
        gust_base: 0.44,
        gust_gain: 0.50,
        visibility_factor: 0.12,
        tags: &["weather.dust_storm", "visibility.very_low", "wind.strong"],
        required_assets: &[
            "weather/dust.yweather@front",
            "audio/weather.ybank@wind_heavy",
        ],
        phenomena: PHENOMENA_DUST,
    },
];
