use crate::visual_asset_catalog::GAME_READY_SKYDOME_VISUALS;

use super::EnvironmentProfileDescriptor;

pub(super) const PROFILES: &[EnvironmentProfileDescriptor] = &[
    EnvironmentProfileDescriptor {
        id: "environment.game_ready_forest_road",
        region: "game_ready.forest_road",
        biome: "temperate_forest",
        weather_table_ref: "weather/game_ready_forest_road.yweather@table",
        sky_profile_ref: "sky/temperate_forest_morning.ysky@gradient",
        cloud_profile_ref: "clouds/temperate_cumulus.ycloud@profile",
        wind_profile_ref: "wind/forest_canopy_breeze.ywind@profile",
        visual_assets: &GAME_READY_SKYDOME_VISUALS,
        latitude_degrees: 45.0,
        axial_tilt_degrees: 23.44,
    },
    EnvironmentProfileDescriptor {
        id: "environment.game_ready_highlands",
        region: "game_ready.highlands",
        biome: "highlands",
        weather_table_ref: "weather/game_ready_highlands.yweather@table",
        sky_profile_ref: "sky/highlands_day.ysky@gradient",
        cloud_profile_ref: "clouds/highlands_fields.ycloud@profile",
        wind_profile_ref: "wind/highlands_breeze.ywind@profile",
        visual_assets: &GAME_READY_SKYDOME_VISUALS,
        latitude_degrees: 45.0,
        axial_tilt_degrees: 23.44,
    },
    EnvironmentProfileDescriptor {
        id: "environment.default",
        region: "world.default",
        biome: "temperate",
        weather_table_ref: "weather/default_temperate.yweather@table",
        sky_profile_ref: "sky/default_temperate.ysky@gradient",
        cloud_profile_ref: "clouds/default_temperate.ycloud@profile",
        wind_profile_ref: "wind/default_breeze.ywind@profile",
        visual_assets: &GAME_READY_SKYDOME_VISUALS,
        latitude_degrees: 38.0,
        axial_tilt_degrees: 23.44,
    },
    EnvironmentProfileDescriptor {
        id: "environment.alpine_winter",
        region: "world.alpine",
        biome: "alpine",
        weather_table_ref: "weather/alpine_winter.yweather@table",
        sky_profile_ref: "sky/alpine_winter.ysky@gradient",
        cloud_profile_ref: "clouds/alpine_winter.ycloud@profile",
        wind_profile_ref: "wind/alpine_gusts.ywind@profile",
        visual_assets: &GAME_READY_SKYDOME_VISUALS,
        latitude_degrees: 58.0,
        axial_tilt_degrees: 23.44,
    },
    EnvironmentProfileDescriptor {
        id: "environment.desert_dusk",
        region: "world.desert",
        biome: "desert",
        weather_table_ref: "weather/desert_dust.yweather@table",
        sky_profile_ref: "sky/desert_dusk.ysky@gradient",
        cloud_profile_ref: "clouds/desert_dust.ycloud@profile",
        wind_profile_ref: "wind/desert_front.ywind@profile",
        visual_assets: &GAME_READY_SKYDOME_VISUALS,
        latitude_degrees: 27.0,
        axial_tilt_degrees: 23.44,
    },
];
