[package]
name = "aurelia-ui-test"
version = "0.1.0"
edition = "2021"
description = "North Star Engine minimal Aurelia UI runtime test application"
authors = ["Take Some()"]
license = "Proprietary"

[dependencies]
newengine-ulog-api = { workspace = true }
newengine-core = { workspace = true }
newengine-engine-runtime = { workspace = true }
newengine-runtime-host = { workspace = true, default-features = false, features = ["full-runtime"] }
newengine-windowed-host-runtime = { workspace = true, default-features = false, features = ["prestart-window-egui", "window-icon"] }
newengine-render-runtime-adapter = { workspace = true }
newengine-scene = { workspace = true }
newengine-scene-runtime = { workspace = true }
newengine-ui = { workspace = true, features = ["provider-null"] }
newengine-ui-api = { workspace = true }
newengine-assets = { workspace = true }
newengine-assets-api = { workspace = true }
newengine-assets-ui-runtime = { workspace = true }
newengine-plugin-host = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
