pub const STARTUP_SETTINGS_SCHEMA_VERSION: u32 = 3;

pub const ENV_GRAPHICS_PRESET: &str = "NEWENGINE_GRAPHICS_PRESET";
pub const ENV_RENDER_SCALE: &str = "NEWENGINE_GRAPHICS_RENDER_SCALE";
pub const ENV_MSAA_SAMPLES: &str = "NEWENGINE_GRAPHICS_MSAA_SAMPLES";
pub const ENV_FXAA_ENABLED: &str = "NEWENGINE_GRAPHICS_FXAA_ENABLED";
pub const ENV_FXAA_EDGE_THRESHOLD: &str = "NEWENGINE_GRAPHICS_FXAA_EDGE_THRESHOLD";
pub const ENV_FXAA_EDGE_THRESHOLD_MIN: &str = "NEWENGINE_GRAPHICS_FXAA_EDGE_THRESHOLD_MIN";
pub const ENV_FXAA_SUBPIXEL_QUALITY: &str = "NEWENGINE_GRAPHICS_FXAA_SUBPIXEL_QUALITY";
pub const ENV_TAA_ENABLED: &str = "NEWENGINE_GRAPHICS_TAA_ENABLED";
pub const ENV_TAA_FEEDBACK: &str = "NEWENGINE_GRAPHICS_TAA_FEEDBACK";
pub const ENV_TAA_NEIGHBORHOOD_CLAMPING: &str = "NEWENGINE_GRAPHICS_TAA_NEIGHBORHOOD_CLAMPING";
pub const ENV_TAA_JITTER_SCALE: &str = "NEWENGINE_GRAPHICS_TAA_JITTER_SCALE";
pub const ENV_SSAO_ENABLED: &str = "NEWENGINE_GRAPHICS_SSAO_ENABLED";
pub const ENV_SSAO_RADIUS_WS: &str = "NEWENGINE_GRAPHICS_SSAO_RADIUS_WS";
pub const ENV_SSAO_INTENSITY: &str = "NEWENGINE_GRAPHICS_SSAO_INTENSITY";
pub const ENV_SSAO_QUALITY_STEPS: &str = "NEWENGINE_GRAPHICS_SSAO_QUALITY_STEPS";
pub const ENV_SSAO_HALF_RESOLUTION: &str = "NEWENGINE_GRAPHICS_SSAO_HALF_RESOLUTION";
pub const ENV_BLOOM_ENABLED: &str = "NEWENGINE_GRAPHICS_BLOOM_ENABLED";
pub const ENV_BLOOM_THRESHOLD: &str = "NEWENGINE_GRAPHICS_BLOOM_THRESHOLD";
pub const ENV_BLOOM_KNEE: &str = "NEWENGINE_GRAPHICS_BLOOM_KNEE";
pub const ENV_BLOOM_INTENSITY: &str = "NEWENGINE_GRAPHICS_BLOOM_INTENSITY";
pub const ENV_BLOOM_RADIUS: &str = "NEWENGINE_GRAPHICS_BLOOM_RADIUS";
pub const ENV_DOF_ENABLED: &str = "NEWENGINE_GRAPHICS_DOF_ENABLED";
pub const ENV_MOTION_BLUR_ENABLED: &str = "NEWENGINE_GRAPHICS_MOTION_BLUR_ENABLED";
pub const ENV_SUN_RAYS_ENABLED: &str = "NEWENGINE_GRAPHICS_SUN_RAYS_ENABLED";
pub const ENV_SHADOWS_ENABLED: &str = "NEWENGINE_GRAPHICS_SHADOWS_ENABLED";
pub const ENV_SHADOW_QUALITY: &str = "NEWENGINE_GRAPHICS_SHADOW_QUALITY";
pub const ENV_SHADOW_CASCADE_COUNT: &str = "NEWENGINE_GRAPHICS_SHADOW_CASCADE_COUNT";
pub const ENV_SHADOW_MAP_RESOLUTION: &str = "NEWENGINE_GRAPHICS_SHADOW_MAP_RESOLUTION";
pub const ENV_SHADOW_FILTER: &str = "NEWENGINE_GRAPHICS_SHADOW_FILTER";
pub const ENV_SHADOW_MAX_DISTANCE: &str = "NEWENGINE_GRAPHICS_SHADOW_MAX_DISTANCE";
pub const ENV_SHADOW_SOFTNESS: &str = "NEWENGINE_GRAPHICS_SHADOW_SOFTNESS";
pub const ENV_SHADOW_BIAS: &str = "NEWENGINE_GRAPHICS_SHADOW_BIAS";
pub const ENV_SHADOW_NORMAL_BIAS: &str = "NEWENGINE_GRAPHICS_SHADOW_NORMAL_BIAS";
pub const ENV_SHADOW_CONTACT_STRENGTH: &str = "NEWENGINE_GRAPHICS_SHADOW_CONTACT_STRENGTH";
pub const ENV_SHADOW_PCSS_LIGHT_RADIUS_DEGREES: &str =
    "NEWENGINE_GRAPHICS_SHADOW_PCSS_LIGHT_RADIUS_DEGREES";
pub const ENV_SHADOW_PCSS_BLOCKER_RADIUS_TEXELS: &str =
    "NEWENGINE_GRAPHICS_SHADOW_PCSS_BLOCKER_RADIUS_TEXELS";
pub const ENV_SHADOW_PCSS_MAX_FILTER_RADIUS_TEXELS: &str =
    "NEWENGINE_GRAPHICS_SHADOW_PCSS_MAX_FILTER_RADIUS_TEXELS";
pub const ENV_SHADOW_PCSS_BLOCKER_SAMPLES: &str = "NEWENGINE_GRAPHICS_SHADOW_PCSS_BLOCKER_SAMPLES";
pub const ENV_SHADOW_PCSS_FILTER_SAMPLES: &str = "NEWENGINE_GRAPHICS_SHADOW_PCSS_FILTER_SAMPLES";
pub const ENV_SHADOW_PCSS_MIN_FILTER_RADIUS_TEXELS: &str =
    "NEWENGINE_GRAPHICS_SHADOW_PCSS_MIN_FILTER_RADIUS_TEXELS";
pub const ENV_SHADOW_PCSS_STABLE_KERNEL_TEXELS: &str =
    "NEWENGINE_GRAPHICS_SHADOW_PCSS_STABLE_KERNEL_TEXELS";
pub const ENV_LOD_QUALITY: &str = "NEWENGINE_GRAPHICS_LOD_QUALITY";
pub const ENV_LOD_DISTANCE_SCALE: &str = "NEWENGINE_GRAPHICS_LOD_DISTANCE_SCALE";
pub const ENV_TEXTURE_QUALITY: &str = "NEWENGINE_GRAPHICS_TEXTURE_QUALITY";
pub const ENV_ANISOTROPY: &str = "NEWENGINE_GRAPHICS_ANISOTROPY";
pub const ENV_WINDOW_MODE: &str = "NEWENGINE_DISPLAY_WINDOW_MODE";
pub const ENV_VSYNC: &str = "NEWENGINE_DISPLAY_VSYNC";
pub const ENV_REFRESH_RATE_MILLIHZ: &str = "NEWENGINE_DISPLAY_REFRESH_RATE_MILLIHZ";
pub const ENV_HDR_MODE: &str = "NEWENGINE_DISPLAY_HDR_MODE";
pub const ENV_FRAME_LIMIT: &str = "NEWENGINE_DISPLAY_FRAME_LIMIT";
