[package]
name = "newengine-ecs-runtime"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "Runtime-hosted ECS gateway runtime service for NewEngine"

[dependencies]
newengine-runtime-unit-api = { path = "../newengine-runtime-unit-api" }
newengine-ulog-api = { path = "../newengine-ulog-api" }
abi_stable = "0.11"
log = "0.4"
serde_json = "1"

newengine-ecs = { path = "../newengine-ecs" }
newengine-audio-api = { path = "../newengine-audio-api" }
newengine-ecs-api = { path = "../newengine-ecs-api" }
newengine-entity-api = { path = "../newengine-entity-api" }
newengine-scene-runtime = { path = "../newengine-scene-runtime" }
newengine-plugin-api = { path = "../newengine-plugin-api" }
newengine-plugin-host = { path = "../newengine-plugin-host" }
newengine-service-api = { path = "../newengine-service-api" }
newengine-service-kit = { path = "../newengine-service-kit" }
