[package]
name = "newengine-tasks-api"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "Gameplay task gateway DTO contract for North Star Engine"
license = "Proprietary"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
newengine-entity-api = { path = "../newengine-entity-api" }
newengine-service-api = { path = "../newengine-service-api" }
newengine-tags-api = { path = "../newengine-tags-api" }
