[package]
name = "asset-inspector"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
newengine-asset-format-nef8 = { path = "../../crates/newengine-asset-format-nef8" }
newengine-asset-inspector-runtime = { path = "../../crates/newengine-asset-inspector-runtime" }
newengine-assets = { path = "../../crates/newengine-assets" }
newengine-assets-ui-runtime = { path = "../../crates/newengine-assets-ui-runtime" }
newengine-core = { path = "../../crates/newengine-core" }
newengine-engine-runtime = { path = "../../crates/newengine-engine-runtime" }
newengine-plugin-host = { path = "../../crates/newengine-plugin-host" }
newengine-render-ui-bridge = { path = "../../crates/newengine-render-ui-bridge" }
newengine-runtime-host = { path = "../../crates/newengine-runtime-host" }
newengine-schema-runtime = { path = "../../crates/newengine-schema-runtime" }
newengine-scene = { path = "../../crates/newengine-scene", features = ["runtime"] }
newengine-scene-runtime = { path = "../../crates/newengine-scene-runtime" }
newengine-ui = { path = "../../crates/newengine-ui", default-features = false }
