[package]
name = "asset-inspector"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
newengine-asset-inspector-runtime = { workspace = true }
newengine-asset-preview-runtime = { workspace = true }
newengine-viewport-bridge = { workspace = true }
newengine-assets = { workspace = true }
newengine-asset-bootstrap-runtime = { workspace = true }
newengine-assets-ui-runtime = { workspace = true }
newengine-core = { workspace = true }
newengine-definitions-runtime = { workspace = true }
newengine-engine-runtime = { workspace = true }
newengine-material-runtime = { workspace = true }
newengine-material-domain-gameready = { workspace = true }
newengine-model-runtime = { workspace = true }
newengine-plugin-host = { workspace = true }
newengine-runtime-host = { workspace = true, default-features = false, features = ["full-runtime"] }
newengine-windowed-host-runtime = { workspace = true, default-features = false, features = ["prestart-window-egui", "window-icon"] }
newengine-render-runtime-adapter = { workspace = true }
newengine-schema-runtime = { workspace = true }
newengine-scene = { workspace = true, features = ["runtime"] }
newengine-scene-runtime = { workspace = true }
newengine-ulog-api = { workspace = true }
newengine-ui = { workspace = true, default-features = false }
