[package]
name = "newengine-startup-intro-mf"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "Windows Media Foundation startup-intro presenter provider for North Star"

[dependencies]
newengine-startup-intro = { path = "../newengine-startup-intro" }

[target.'cfg(windows)'.dependencies]
windows-core = "0.62.2"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_WindowsAndMessaging",
] }
