[package]
name = "newengine-render-ui-bridge"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "Renderer-neutral engine.ui draw-list bridge for NewEngine"

[dependencies]
newengine-core = { path = "../newengine-core" }
newengine-render-feature-api = { path = "../newengine-render-feature-api" }
