[package]
name = "newengine-plugin-host"
version = "0.1.0"
readme = "README.md"
edition = "2021"

[dependencies]
newengine-runtime-contract-catalog = { path = "../newengine-runtime-contract-catalog" }
newengine-ulog-api = { path = "../newengine-ulog-api" }
log = "0.4.29"
abi_stable = "0.11"
libloading = "0.9.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10"
newengine-plugin-api = { path = "../newengine-plugin-api" }
newengine-platform-api = { path = "../newengine-platform-api" }
newengine-math = { path = "../newengine-math" }
newengine-service-api = { path = "../newengine-service-api" }
newengine-loading-api = { path = "../newengine-loading-api" }
newengine-task-api = { path = "../newengine-task-api" }
