[package]
name = "newengine-math"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["kernel"]
kernel = ["dep:parking_lot", "dep:log"]
serde = ["dep:serde"]

[dependencies]
abi_stable = "0.11.3"
serde = { version = "1.0", features = ["derive"], optional = true }
parking_lot = { version = "0.12", optional = true }
log = { version = "0.4", optional = true }

[lints.rust]
unsafe_op_in_unsafe_fn = "forbid"