[package]
name = "newengine-model-domain-api"
version = "0.1.0"
edition = "2021"
description = "Stable model construction domain contracts for NewEngine"

[dependencies]
serde = { version = "1", features = ["derive"] }
newengine-service-api = { path = "../newengine-service-api" }
newengine-assets-api = { path = "../newengine-assets-api" }

newengine-materials = { path = "../newengine-materials", features = ["serde"] }
newengine-model-skeleton-api = { path = "../newengine-model-skeleton-api" }
newengine-primitives = { path = "../newengine-primitives", features = ["serde"] }
